//  : This file defines the root layout for the Next.js app, including global styles, fonts, and persistent components like Header, Footer, and Whatsapp.
import "./globals.css"; //  : Import global CSS styles for the app.
import "primereact/resources/themes/lara-light-indigo/theme.css"; //  : PrimeReact theme CSS.
import "primereact/resources/primereact.min.css"; //  : PrimeReact core CSS.
import "primeicons/primeicons.css"; //  : PrimeReact icon CSS.
import { Poppins } from "next/font/google"; //  : Import Poppins font from Google Fonts.
import Header from "./Components/Header"; //  : Persistent header component.
import Footer from "./Components/Footer"; //  : Persistent footer component.
import Whatsapp from "./Components/Whatsapp"; //  : Floating WhatsApp chat component.

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
}); //  : Configure the Poppins font with all available weights and Latin subset.

export const metadata = {
  title: "Create Next App", //  : Default page title for the app.
  description: "Generated by create next app", //  : Default page description.
};

export default function RootLayout({ children }) {
  //  : The root layout wraps all pages with global styles, header, footer, and WhatsApp chat.
  return (
    <html lang="en" className={poppins.className}>
      <body className="font-main">
        <Header /> {/*  : Persistent header at the top of every page. */}
        <Whatsapp /> {/*  : Floating WhatsApp chat button. */}
        {children} {/*  : Render the current page's content here. */}
        <Footer /> {/*  : Persistent footer at the bottom of every page. */}
      </body>
    </html>
  );
}
